class Hyperparameters():
    MAX_NODES = 2**20

    C1 = 1
    C2 = 1
    C3 = 1

    MAX_SPECIES_DISTANCE = 4

    WEIGHT_SHIFT_STRENGTH = 0.3
    WEIGHT_RANDOM_STRENGTH = 1

    PROBABILIY_SURVIVE_KILL_SPECIES = 0.8

    PROBABILITY_MUTATE_LINK = 0.01
    PROBABILITY_MUTATE_NODE = 0.003
    PROBABILITY_MUTATE_WEIGHT_SHIFT = 0.002
    PROBABILITY_MUTATE_WEIGHT_RANDOM = 0.002
    PROBABILITY_MUTATE_TOGGLE_LINK = 0.002